# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Styx < Formula
  desc "Personal cloud platform for macOS"
  homepage "https://github.com/kessler-frost/styx"
  version "2025.12.14"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/kessler-frost/styx/releases/download/2025.12.14/styx_2025.12.14_darwin_arm64.tar.gz"
    sha256 "11e1ce321b2f36e61af64948da86fe790085cc7e7ae06995e86f7190ab6eb9d6"

    def install
      bin.install "styx"
      (lib/"styx/plugins").install "apple-container"
    end
  end

  def caveats
    <<~EOS
      The Nomad driver plugin has been installed to:
        #{lib}/styx/plugins/apple-container

      Configure Nomad to find it by adding to your Nomad config:
        plugin_dir = "#{lib}/styx/plugins"

      Or run 'styx init' which handles this automatically.
    EOS
  end

  test do
    system "#{bin}/styx", "version"
  end
end
